theme = "blowfish" # UNCOMMENT THIS LINE
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

googleAnalytics = "G-0PXDGGP7FP"

[pagination]
pagerSize = 30

[imaging]
anchor = 'Center'

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[outputs]
home = ["HTML", "RSS", "JSON"]

[related]
threshold = 0
toLower = true
includeNewer = true

[[related.indices]]
name = "title"
weight = 50

[[related.indices]]
name = "date"
weight = 5

[[related.indices]]
name = "description"
weight = 30

[[related.indices]]
name = "tags"
weight = 70

[[related.indices]]
name = "series"
weight = 90