# Hindi (hi)
disabled = false
languageCode = "hi"
languageName = "рд╣рд┐рдиреНрджреА"
weight = 6
title = "Blowfish"

[params]
displayName = "рд╣рд┐рдиреНрджреА"
rtl = false
dateFormat = "2 рдЬрдирд╡рд░реА 2006"
logo = "img/logo.png"
description = "рдХрдВрдкреНрдпреВрдЯрд░ рд╡рд┐рдЬреНрдЮрд╛рди рдФрд░ рдПрд▓реНрдЧреЛрд░рд┐рджрдо рдХреЗ рдмрд╛рд░реЗ рдореЗрдВ рдбреЗрд╡рд┐рдб рдЬрд╝рд╛рдВрдЧ рдХрд╛ рдбреЗрд╡рд▓рдкрдореЗрдВрдЯ рд▓реЙрдЧред"
copyright = "CC BY-NC-SA 4.0"

[params.author]
name = "David (Ziyuan) Zhang"
email = "davidzhang20001112@gmail.com"
image = "img/author.png"
headline = "рд╕реЙрдлреНрдЯрд╡реЗрдпрд░ рдЗрдВрдЬреАрдирд┐рдпрд░ЁЯСитАНЁЯТ╗ @RobloxЁЯЪА, рд▓рд╛рдЦреЛрдВ рд╡реИрд╢реНрд╡рд┐рдХ рдЙрдкрдпреЛрдЧрдХрд░реНрддрд╛рдУрдВЁЯМН рдХреЗ рд▓рд┐рдП рд▓реЛ-рд▓реЗрдЯреЗрдВрд╕реАтЪб, рдмрдбрд╝реЗ рдкреИрдорд╛рдиреЗЁЯМР, рд╡рд┐рддрд░рд┐рдд рд░реАрдпрд▓-рдЯрд╛рдЗрдоЁЯУК рд╕рд┐рдлрд╛рд░рд┐рд╢ рд╕рд┐рд╕реНрдЯрдо рдмрдирд╛ рд░рд╣реЗ рд╣реИрдВред"
links = [
    { github = "https://github.com/wacry" },
    { acm = "https://icpc.global/ICPCID/6RP5EXAXJZWB" },
    { linkedin = "https://www.linkedin.com/in/dz00/" },
    { email = "mailto:davidzhang20001112@gmail.com" },
    { ko-fi = "https://buymeacoffee.com/davidzhangu" }
    #    { facebook = "https://facebook.com/username" },
    #    { mastodon = "https://mastodon.instance/@username" },
    #    { medium = "https://medium.com/username" },
    #    { microsoft = "https://www.microsoft.com/" },
    #    { patreon = "https://www.patreon.com/username" },
    #    { pinterest = "https://pinterest.com/username" },
    #    { reddit = "https://reddit.com/user/username" },
    #    { slack = "https://workspace.url/team/userid" },
    #    { snapchat = "https://snapchat.com/add/username" },
    #    { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    #    { telegram = "https://t.me/username" },
    #    { threads = "https://www.threads.net/@username" },
    #    { tiktok = "https://tiktok.com/@username" },
    #    { twitter = "https://twitter.com/username" },
    #    { x-twitter = "https://twitter.com/username" },
    #    { whatsapp = "https://wa.me/phone-number" },
    #    { youtube = "https://youtube.com/username" },
    #    { codeberg = "https://codeberg.org/username" },
]
