# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.extensions]
tableOfContents = true
definitionList = true
footnote = true
strikethrough = true
taskList = true
autolink = true
linkify = true

[goldmark.renderer]
unsafe = true

[goldmark.extensions.passthrough]
enable = true

[goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[highlight]
noClasses = true
lineNos = true
lineNumbersInTable = false
style = "dracula"

[tableOfContents]
startLevel = 2
endLevel = 4