[[main]]
name = "Tüm Gönderiler"
pageRef = "posts"
weight = 10

[[main]]
name = "Kategoriler"
pageRef = "categories"
weight = 20

[[main]]
name = "Etiketler"
pageRef = "tags"
weight = 30

[[main]]
name = "Seriler"
pageRef = "series"
weight = 40
