[[main]]
name = "Tutti i Post"
pageRef = "posts"
weight = 10

[[main]]
name = "Categorie"
pageRef = "categories"
weight = 20

[[main]]
name = "Tag"
pageRef = "tags"
weight = 30

[[main]]
name = "Serie"
pageRef = "series"
weight = 40
