[[main]]
name = "Tất cả bài viết"
pageRef = "posts"
weight = 10

[[main]]
name = "Danh mục"
pageRef = "categories"
weight = 20

[[main]]
name = "Thẻ"
pageRef = "tags"
weight = 30

[[main]]
name = "Loạt bài"
pageRef = "series"
weight = 40
