[[main]]
name = "Tous les Articles"
pageRef = "posts"
weight = 10

[[main]]
name = "Catégories"
pageRef = "categories"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 30

[[main]]
name = "Séries"
pageRef = "series"
weight = 40
