[[main]]
name = "Todas las Publicaciones"
pageRef = "posts"
weight = 10

[[main]]
name = "Categorías"
pageRef = "categories"
weight = 20

[[main]]
name = "Etiquetas"
pageRef = "tags"
weight = 30

[[main]]
name = "Series"
pageRef = "series"
weight = 40
