[[main]]
name = "Todas as Postagens"
pageRef = "posts"
weight = 10

[[main]]
name = "Categorias"
pageRef = "categories"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 30

[[main]]
name = "Séries"
pageRef = "series"
weight = 40
