[[main]]
name = "Все записи"
pageRef = "posts"
weight = 10

[[main]]
name = "Категории"
pageRef = "categories"
weight = 20

[[main]]
name = "Теги"
pageRef = "tags"
weight = 30

[[main]]
name = "Серии"
pageRef = "series"
weight = 40
