[[main]]
name = "Alle Beiträge"
pageRef = "posts"
weight = 10

[[main]]
name = "Kategorien"
pageRef = "categories"
weight = 20

[[main]]
name = "Tags"
pageRef = "tags"
weight = 30

[[main]]
name = "Serien"
pageRef = "series"
weight = 40
